name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Get Apt packages
      run: >
        sudo apt-get update -y &&
        sudo apt-get install -y --no-install-recommends
        vim
        git
        gcc-13
        g++-13
        build-essential
        cmake
        unzip
        tar
        ca-certificates
        doxygen
        graphviz
        pipx

    - name: Conan installation
      run: pipx install conan

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Cache Conan
      uses: actions/cache@v4
      with:
        path: ~/.conan2/p
        key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.txt') }}
        restore-keys: |
          ${{ runner.os }}-conan-

    - name: Conan install dependencies
      run: >
        conan install conanfile.py 
        --profile:build=conan/profiles/linux-x86-gcc13-debug 
        --profile:host=conan/profiles/linux-x86-gcc13-debug 
        --build=missing
        --output-folder=build

    - name: CMake configuration
      run:  >
        cmake 
        -B ${{github.workspace}}/build 
        -S .
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DBUILD_TESTS=ON
        --toolchain ${{github.workspace}}/build/conan_toolchain.cmake

    - name: CMake build
      run:  >
        cmake 
        --build ${{github.workspace}}/build 
        --config ${{env.BUILD_TYPE}}

    - name: CMake test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure

    - name: Doxygen documentation generation
      working-directory: ${{github.workspace}}/build
      run: make docs

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{github.workspace}}/build/docs/html
